FROM node:20 AS dev

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN apt update && apt install -y xdg-utils dbus-x11
COPY . .
EXPOSE 4200
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200"]