# 🔹 Etap 1: Budowanie aplikacji
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm install
RUN npm run build --configuration=production

# 🔹 Etap 2: Serwowanie aplikacji przez Nginx
FROM nginx:latest
COPY --from=build /app/dist/scrum-master-ui /usr/share/nginx/html

# 🔹 Konfiguracja Nginx dla Angulara
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
